# Generated by Django 3.1.2 on 2020-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_1', models.CharField(default='', max_length=80)),
                ('location_2', models.CharField(default='', max_length=80)),
                ('discription', models.CharField(default='', max_length=80)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('severity', models.CharField(default='', max_length=80)),
                ('casue', models.CharField(default='', max_length=80)),
                ('action', models.CharField(default='', max_length=80)),
                ('type_env', models.BooleanField(default=False)),
                ('type_inj', models.BooleanField(default=False)),
                ('type_prop', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('reported_by', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
